version: '3.8'

services:
  # Base de donn√©es MySQL
  db:
    image: mysql:8.0
    container_name: altra_mysql
    restart: "no"
    environment:
      MYSQL_DATABASE: altra_wordpress
      MYSQL_USER: altra_user
      MYSQL_PASSWORD: altra_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - altra_network

  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: altra_wordpress
    restart: "no"
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: altra_wordpress
      WORDPRESS_DB_USER: altra_user
      WORDPRESS_DB_PASSWORD: altra_password
      WORDPRESS_DEBUG: '1'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    volumes:
      # Monte tout le dossier wordpress en local
      - ./wordpress:/var/www/html
      # Configuration PHP pour augmenter les limites d'upload
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - altra_network

networks:
  altra_network:
    driver: bridge
